"""
Django settings for futgo_core project.

Generated by 'django-admin startproject' using Django 4.2.29.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sua-chave-secreta-aqui-mude-em-producao'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] # Permite acesso de qualquer host em modo de desenvolvimento


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Bibliotecas de Terceiros
    'rest_framework',
    'corsheaders', # <-- BIBLIOTECA DE CORS (Resolve o NetworkError)
    
    # As suas apps
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # <-- DEVE SER O PRIMEIRO DA LISTA!
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'futgo_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'futgo_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Mantemos o SQLite3 apenas para as tabelas internas do Django. 
# Os seus utilizadores e produtos estão no Firebase Firestore!
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'pt-pt'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==========================================
# CONFIGURAÇÕES DE CORS (SEGURANÇA DO NAVEGADOR)
# ==========================================
# Permite que qualquer Frontend local (como o seu React na porta 5173 ou 3000) aceda à API
CORS_ALLOW_ALL_ORIGINS = True 

# Importa os cabeçalhos padrão e adiciona o nosso customizado para o Admin
from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-user-id', # <-- ESTE É O CABEÇALHO QUE DESBLOQUEIA O PAINEL DE ADMIN!
]


# ==========================================
# CONFIGURAÇÕES DE ENVIO DE E-MAIL (GMAIL)
# ==========================================
# Altere as credenciais abaixo para testar o envio real de OTPs
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'pirotivitor3@gmail.com' # ⬅️ COLOQUE O SEU GMAIL AQUI
EMAIL_HOST_PASSWORD = 'ynfz xbas rytr binv' # ⬅️ COLOQUE A SENHA DE APP DO GMAIL AQUI